### ISSUE TITLE
Team Meetup & Work Distribution

### ISSUE THREAD

**Issue by ahurley7** [IntroToCode/CodeMates5_Spring23#1]
## 💬 Discussion topic

Come up with plan to divide workload and facilitate participation

## ❗ Potential issues

None - Primary objective is to organize team effort

## 👥 People to consult

@ahurley7 
@jahnavishah121-coder 
@URIELGSN 
@romolina94
@annakim222

## 📃 Details

For Breakfast Recipe: (TBD for actual selection of recipe)

-- Ingredients & Time to Prepare: romolina94
-- Sequences: URIELGSN
-- Equipment: annakim222

For Dinner Recipe: (TBD for actual selection of recipe)

-- Ingredients & Time to Prepare: jahnavishah121-coder
-- Sequences: ahurley7
-- Equipment: annakim222

Please feel to use this forum to address subsequent issues or changes in assigned responsibilities

**Comment by ahurley7** [comment]
As a follow up to the initial distribution of work, it appears we are outside of the assignment guidelines since **everyone** needs to contribute to **_BOTH_** recipe files.

To rectify this issue, I propose the following revision to the contributions covered by each member of the team:

### Breakfast Recipe Updates:      

- Recipe Title: Andrew
- Servings: Anna
- Time: Uriel
- Ingredients: Jahnavi
- Equipment: Maria
- Steps: Anna
- Notes: Andrew

### Dinner Recipe Updates:

- Recipe Title: Jahnavi
- Servings: Maria
- Time: Maria
- Ingredients: Anna
- Equipment: Uriel
- Steps: Andrew
- Notes: Andrew

**Comment by ahurley7** [comment]
To make the acceptance criteria fully explicit, the following expectations are in place for pull request approvals:
- Content submitted aligns with section assignments listed in previous comments
- Formatting is streamlined and readable (i.e. spacing, returns, and whitespace used to separate entries and tasks clearly)
- Bulleted lists used for Ingredients and Equipment sections
- Numbered list used for Preparation Steps section
- Referenced URL's show as expected

**Comment by jahnavishah121-coder** [comment]
I have reviewed all the merge results for the recipes. They look good. I have also completed all my assigned tasks.

**Comment by romolina94** [comment]
I completed my review and have no concerns. Completed assigned tasks for breakfast and dinner files

**Comment by URIELGSN** [comment]
I completed my review and have no concerns. Completed assigned tasks for breakfast and dinner files

**Comment by annakim222** [comment]
I completed my review and didn't find any related issues. Completed assigned tasks for breakfast and dinner files

**Comment by ahurley7** [comment]
Thanks everyone for knocking out assigned content!  I'll be leaving this issue in an open state for the sake of visibility and for ease of reference for those executing grading.  This comment confirms the following:

- Everyone has at least one commit & pull request associated with both the Breakfast and Dinner recipe files
- Both recipes are complete and validated in accordance with stated acceptance criteria
- All other issues that were identified have been corrected and moved to a closed state

It's been great working with all of you! 👍

**Comment by annakim222** [comment]
Thank you Andrew!! See you in class!! :)

**Comment by ahurley7** [comment]
Per discussion with Aparna  - moving this log to closed state so its clear that there are no outstanding or unresolved issues
