### ISSUE TITLE
Preferred Name Verification for Recording Team Members

### ISSUE THREAD

**Issue by ahurley7** [IntroToCode/CodeMates5_Spring23#12]
## 💬 Discussion topic

When adding team names to the associated readme files for breakfast & dinner, @romolina94 was identified as "Maria Molina"; however, her name shows as "Rosario Molina" in her GitHub profile. 

## ❗ Potential issues

- Need to confirm that team member's preferred name is used in the submitted files

## 👥 People to consult

@romolina94 

## 📃 Details

- Codemates team number and team names is entered in the last line of each recipe file
- romolina94 was identified as "Maria Molina" which is inconsistent with stated name in GitHub profile
- Need to confirm preferred name for final submission

**Comment by romolina94** [comment]
I prefer to be named as Rosario please
@jahnavishah121-coder could you do this update tonight?

**Comment by jahnavishah121-coder** [comment]
No problem. I will do this in my updates.

**Comment by jahnavishah121-coder** [comment]
I have made the fixes in both the breakfast and dinner file. They have both been approved/ merged. I am going to close the issue log.
