### ISSUE TITLE
Incorrect formatting for the servings and time entries

### ISSUE THREAD

**Issue by jahnavishah121-coder** [IntroToCode/CodeMates5_Spring23#13]
## 💬 Discussion topic

Servings and time entries should be listed below the header level.

## ❗ Potential issues

Accessibility and aesthetics improvement

## 👥 People to consult

@ahurley7 
@romolina94 

## 📃 Details

Entries for servings and time look better when they are separated from the header line.

**Comment by romolina94** [comment]
Yes, I agree, I think we could have both entries below headers

**Comment by ahurley7** [comment]
Initially, I disagreed with this recommendation; however reviewing examples from other Codemates repositories makes it clear that this is easier to read and more approachable.  Jahnavi: would you mind updating this tonight in your pull requests?

**Comment by jahnavishah121-coder** [comment]
I ll take care of this one as well!

**Comment by jahnavishah121-coder** [comment]
I have made the changes as requested. Closing this issue. Please ropen a new issue if need be.
